{% set version = "1.2.15" %}

package:
  name: alsa-lib
  version: {{ version }}

source:
  url: https://github.com/alsa-project/alsa-lib/archive/v{{ version }}.tar.gz
  sha256: 7226c4da8de1596ee7cd82480999c462c9b6fba98cb40332255049ed9bde9aee

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=alsa
    # Seems like they accidentally broke patch version ABI compatibility
    # and quickly fixed it.
    - {{ pin_subpackage("alsa-lib", max_pin="x.x") }}

requirements:
  build:
    - make
    - autoconf
    - automake
    - libtool
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libasound$SHLIB_EXT

about:
  home: http://www.alsa-project.org/main/index.php/Main_Page
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: COPYING
  summary: Advanced Linux Sound Architecture

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
    - ryanvolz
